export const PROS_TEXT = [
  'They can be low-maintenance',
  'Cats are loyal friends',
  'They can be affectionate',
  'Cats are fine left home alone',
  'Cats love playing',
  'They are entertaining',
  'Cats comfort you if you\'re worried or feel alone',
  'They may help control pests',
  'Owning a cat can reduce your overall stress level',
  'Cats can keep themselves busy',
  'They are cute when young',
  'Owning a cat can help you to become more responsible',
  'Cats can make you laugh',
  'They don\'t require that much space',
  'You don\'t have to walk them',
  'Getting a cat can be nice if you have children',
  'Cat food is generally cheaper than dog food',
  'A self-cleaning pet: cats are constantly bathing themselves',
  'Getting a cat can help you overcome difficult times in your life',
  'You can cuddle your cat',
];

export const CONS_TEXT = [
  'Their litter boxes are smelly and must be cleaned regularly',
  'They damage furniture',
  'Many people are allergic to them',
  'Veterinary care is expensive',
  'They may kill small animals',
  'They are strong-willed',
  'They vomit occasionally',
  'Difficulties if you want to rent a flat',
  'They may wake you up',
  'They can be very vocal',
  'They can get fleas',
  'Cat hair in your home',
  'I can’t travel as freely as I did before',
  'They may scratch or bite',
  'Your cat may get lost',
  'Can be a bit aloof',
  'Your home may smell rather bad',
  'Your cat may get involved in an accident',
  'Cats may not obey',
  'Getting a cat is a long-term commitment',
];
